name = "SimJulia"
uuid = "428bdadb-6287-5aa5-874b-9969638295fd"
keywords = ["discrete-even simulation"]
license = "MIT"
desc = "A discrete event process oriented simulation framework."
version = "0.8"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"

[compat]
julia = ">=1.2"
ResumableFunctions = ">=0.5.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
